USE [master]
GO
/****** Object:  Database [DapperIntro]    Script Date: 06-Jul-21 7:05:28 AM ******/
CREATE DATABASE [DapperIntro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DapperIntro', FILENAME = N'G:\SQL\DapperIntro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DapperIntro_log', FILENAME = N'G:\SQL\DapperIntro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DapperIntro] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DapperIntro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DapperIntro] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DapperIntro] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DapperIntro] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DapperIntro] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DapperIntro] SET ARITHABORT OFF 
GO
ALTER DATABASE [DapperIntro] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DapperIntro] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DapperIntro] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DapperIntro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DapperIntro] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DapperIntro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DapperIntro] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DapperIntro] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DapperIntro] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DapperIntro] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DapperIntro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DapperIntro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DapperIntro] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DapperIntro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DapperIntro] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DapperIntro] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DapperIntro] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DapperIntro] SET RECOVERY FULL 
GO
ALTER DATABASE [DapperIntro] SET  MULTI_USER 
GO
ALTER DATABASE [DapperIntro] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DapperIntro] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DapperIntro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DapperIntro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DapperIntro] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DapperIntro', N'ON'
GO
ALTER DATABASE [DapperIntro] SET QUERY_STORE = OFF
GO
USE [DapperIntro]
GO
/****** Object:  Table [dbo].[Addresses]    Script Date: 06-Jul-21 7:05:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Addresses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Street] [nvarchar](50) NOT NULL,
	[PersonId] [int] NOT NULL,
 CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[People]    Script Date: 06-Jul-21 7:05:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Addresses] ON 
GO
INSERT [dbo].[Addresses] ([Id], [Street], [PersonId]) VALUES (1, N'Street 1', 1)
GO
INSERT [dbo].[Addresses] ([Id], [Street], [PersonId]) VALUES (2, N'Street 2', 1)
GO
SET IDENTITY_INSERT [dbo].[Addresses] OFF
GO
SET IDENTITY_INSERT [dbo].[People] ON 
GO
INSERT [dbo].[People] ([Id], [Name], [Email]) VALUES (1, N'Felipe', N'felipe@hotmail.com')
GO
SET IDENTITY_INSERT [dbo].[People] OFF
GO
ALTER TABLE [dbo].[Addresses]  WITH CHECK ADD  CONSTRAINT [FK_Addresses_People] FOREIGN KEY([PersonId])
REFERENCES [dbo].[People] ([Id])
GO
ALTER TABLE [dbo].[Addresses] CHECK CONSTRAINT [FK_Addresses_People]
GO
USE [master]
GO
ALTER DATABASE [DapperIntro] SET  READ_WRITE 
GO